//
//  PfizerLogo.m
//  EasyCall
//
//  Created by Walter Vargas-Pena on 5/1/13.
//
//

#import "PfizerLogo.h"

@implementation PfizerLogo

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
        self.fillColor = kPFizerLogoBlue;
        self.backgroundColor = [UIColor clearColor];
    }
    return self;
}


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect
{
    //// Color Declarations
    
    //// Frames
    CGRect frame = rect;
    
    
    //// Bezier 104 Drawing
    UIBezierPath* bezier104Path = [UIBezierPath bezierPath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24314 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36885 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18714 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36885 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.12773 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58845 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.18714 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36885 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.13654 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55584 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17590 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58845 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19705 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51026 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17891 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57729 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.18733 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54621 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32784 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44392 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29569 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51011 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31884 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48255 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24314 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36885 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33512 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41269 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32906 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36885 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44235 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.20337 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48691 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.26559 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48019 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.24158 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48681 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.22939 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39069 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21274 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45228 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.22249 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41622 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23779 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39069 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44235 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.28324 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39070 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.28700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41140 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88651 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43942 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83604 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47133 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.86760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43942 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84704 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45801 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84444 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44196 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79767 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44196 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75812 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58846 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80635 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58846 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82496 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52009 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83212 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50119 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82635 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51522 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.82880 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50839 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85126 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47298 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49074 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84352 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47986 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86922 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46627 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.85699 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46791 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86249 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46520 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87580 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47501 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87389 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46702 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87523 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47096 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48669 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87626 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47848 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87694 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48264 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89528 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49181 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.88256 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48825 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.88646 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49181 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91711 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46752 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.90694 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49181 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.91711 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48192 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88651 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43942 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45525 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.91311 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43942 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63171 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44195 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51183 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44195 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50535 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46598 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57222 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46599 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58845 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55749 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48868 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.48001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54216 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60271 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58845 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49632 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58845 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60271 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58845 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61062 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55898 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53508 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55898 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61062 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55898 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54549 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55898 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63171 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44195 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55299 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52451 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61791 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48751 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71479 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49668 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66936 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50958 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70347 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50556 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69117 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50883 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69413 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46976 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67295 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49341 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68216 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47896 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71526 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46148 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70125 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46428 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70993 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46148 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72953 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47215 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72697 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46148 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72953 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46799 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71479 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49668 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72954 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47973 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72496 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48871 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74046 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54281 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69433 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56591 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73797 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71679 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56591 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66557 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53970 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67759 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56591 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66557 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55383 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66595 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52897 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66557 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53669 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66531 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53453 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72375 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52067 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69239 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52897 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70815 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52588 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76537 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47033 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74880 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51254 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76537 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49114 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71810 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43847 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76537 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45026 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74346 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43847 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61936 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53670 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43847 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61936 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48367 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68050 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59329 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61936 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57050 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64404 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59329 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72609 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58255 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69732 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59329 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71268 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58952 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74880 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56513 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73460 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57813 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74209 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57209 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74046 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54281 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    [bezier104Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95083 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43174 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54817 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74159 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55913 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.77621 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69402 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38967 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75855 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49354 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75298 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44007 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75844 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31389 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75446 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36349 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75860 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33815 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75721 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38886 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46600 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.43579 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46600 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40294 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58846 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58846 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49008 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44196 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45669 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56662 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47768 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48687 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39527 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44196 * CGRectGetHeight(frame))];
    [bezier104Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38609 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36459 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41246 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37547 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36925 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45088 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33087 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42439 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34461 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43643 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33312 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46688 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34102 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46258 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32905 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46684 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33634 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45977 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36439 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46697 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35016 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45966 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35206 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38721 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45985 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37346 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46569 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38721 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51506 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35600 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50270 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38721 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51413 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37471 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50026 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32753 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34696 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51378 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33701 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44314 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31686 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.48593 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31748 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46033 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31532 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37489 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36315 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41153 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31972 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38897 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33937 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34708 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44014 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36409 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38154 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35800 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39788 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26720 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74724 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34708 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44014 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.29141 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65386 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.05379 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58951 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.15269 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72446 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.07026 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66843 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.05082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56056 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.05179 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57993 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.05081 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57026 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44613 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25247 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.05088 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43353 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.21863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29991 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60811 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23537 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50166 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24088 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55638 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23538 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94795 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40366 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.78445 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23537 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92618 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29923 * CGRectGetHeight(frame))];
    [bezier104Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95083 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43174 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94989 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41295 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.95084 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42233 * CGRectGetHeight(frame))];
    [bezier104Path closePath];
    bezier104Path.miterLimit = 4;
    
    [self.fillColor setFill];
    [bezier104Path fill];
    
    
}


@end
